services:
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    platform: linux/arm64
    ports:
      - "8888:8888"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    command: >
      /usr/local/bin/envoy
        -c /etc/envoy/envoy.yaml
        --service-node grpc-web-proxy
        --service-cluster grpc-web-to-grpc
        --log-level info
    environment:
      - GRPC_BACKEND_HOST=host.docker.internal
      - GRPC_BACKEND_PORT=50052
    restart: unless-stopped